# Generated by Django 3.2 on 2022-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll', models.IntegerField(unique=True)),
                ('dept', models.CharField(max_length=70)),
                ('marks', models.FloatField()),
                ('pass_date', models.DateField()),
            ],
        ),
    ]
