# Generated by Django 3.2 on 2022-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelRelationship', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=80)),
                ('song_duration', models.IntegerField()),
                ('user', models.ManyToManyField(to='modelRelationship.User')),
            ],
        ),
    ]
