# Generated by Django 3.2 on 2022-12-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
