# Generated by Django 3.2 on 2022-12-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0005_st'),
    ]

    operations = [
        migrations.DeleteModel(
            name='St',
        ),
    ]
