# Generated by Django 3.2 on 2022-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0007_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
