# Generated by Django 3.2 on 2022-12-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0008_tracher'),
    ]

    operations = [
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_clr', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parents_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelsRelationship_2.parents')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            bases=('ModelsRelationship_2.parents',),
        ),
    ]
