# Generated by Django 3.2 on 2022-12-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0010_father_son'),
    ]

    operations = [
        migrations.CreateModel(
            name='daughter',
            fields=[
                ('father_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelsRelationship_2.father')),
                ('height', models.FloatField()),
            ],
            bases=('ModelsRelationship_2.father',),
        ),
    ]
