# Generated by Django 3.2 on 2022-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsRelationship_2', '0011_daughter'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=70)),
                ('marks', models.IntegerField()),
                ('pass_date', models.DateField()),
                ('admitdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('empnum', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='parents_ptr',
        ),
        migrations.RemoveField(
            model_name='daughter',
            name='father_ptr',
        ),
        migrations.DeleteModel(
            name='St',
        ),
        migrations.DeleteModel(
            name='Tracher',
        ),
        migrations.DeleteModel(
            name='son',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='daughter',
        ),
        migrations.DeleteModel(
            name='father',
        ),
        migrations.DeleteModel(
            name='parents',
        ),
    ]
