# Generated by Django 5.0.6 on 2024-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontainer',
            name='profilelist',
            field=models.ManyToManyField(to='myapp.userprofile'),
        ),
    ]
