# Generated by Django 3.2 on 2022-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='daughter',
            fields=[
            ],
            options={
                'ordering': ['age'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelManager.mother',),
        ),
    ]
