# Generated by Django 3.2 on 2022-09-20 09:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('modelManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mother',
            managers=[
                ('objCM', django.db.models.manager.Manager()),
            ],
        ),
    ]
