# Generated by Django 3.2 on 2022-09-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('clr', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='son',
            fields=[
            ],
            options={
                'ordering': ['age'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ModelInheritance.father',),
        ),
    ]
