# Generated by Django 4.2.3 on 2023-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("national_id", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
