# Generated by Django 5.0.1 on 2024-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
