# Generated by Django 5.0.1 on 2024-01-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_processor_size_alter_ram_size_alter_ssd_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.ManyToManyField(blank=True, to='myapp.processor')),
            ],
        ),
    ]
